name: SonarCloud analysis

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read
  security-events: write

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=gracekarinn_adpro
            -Dsonar.organization=gracekarinn
            -Dsonar.verbose=true
            -Dsonar.analysis.resultFile=results.sarif
            -Dsonar.externalIssuesReportPaths=results.sarif
            -Dsonar.sarif.path=results.sarif
          projectBaseDir: .

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: results.sarif